### ISSUE TITLE
Icons for entities while in editing.

### ISSUE THREAD

**Issue by SniperGoth** [redeclipse/world#151] opened 2019-12-26 00:59 UTC
What if the entities had icons for them, instead of the random particles they emit?
That way  you could more easily tell what is in a scene/map, without having to check every entity to see what they are about.
Of course they would increase in size if you were closer to them, and smaller the further you were, since it could use the billboard particle effect for that.

Concept art of how it would look like (sorta)
![icon 2](https://user-images.githubusercontent.com/24359960/71452182-22f4c900-2761-11ea-9b4a-9b26dc8d5fc4.png)
![icon 3](https://user-images.githubusercontent.com/24359960/71452183-238d5f80-2761-11ea-96d1-01fc9c31339b.png)
![icon 1](https://user-images.githubusercontent.com/24359960/71452184-238d5f80-2761-11ea-9fb9-d86231c62d50.png)

I strongly feel this would be a good thing to have, and even speed up the process of looking for something in particular without needing to rely on /entfind as much, considering maps can have a incredible amount of them around, as for light/particle entities it could even feature the actual color you use for them.

**Comment by Jigoku** [comment] 2019-12-26 15:04
Would be nice to have higher visibility on non-selected entities, the small purple dot can be hard to spot at times.

**Comment by IceflowRE** [comment] 2019-12-26 15:46
Duplicate of https://github.com/redeclipse/base/issues/51

**Comment by Calinou** [comment] 2019-12-26 16:52
@IceflowRE Should this issue be closed as a duplicate?

**Closed** 2019-12-26 18:06 UTC
Labels: feature request, suggestion
