### ISSUE TITLE
New rifle model

### ISSUE THREAD

**Issue by V-ktor** [redeclipse/world#136] opened 2019-11-01 19:58 UTC
My new rifle model is ready.
Here's a .zip file with all config files. It includes the mesh, a low poly version for item/vwep, animations for the weapon itself and the player model, and the cfg files.
[new_rifle.zip](https://github.com/redeclipse/world/files/3799397/new_rifle.zip)

Screenshots:
![20191101205331](https://user-images.githubusercontent.com/12966454/68052444-f0db6380-fce9-11e9-9ff1-238a3e5dd2f4.jpg)
![20191101205410](https://user-images.githubusercontent.com/12966454/68052453-f3d65400-fce9-11e9-9f3b-ac78529a7d55.jpg)

**Comment by poVoq** [comment] 2019-11-11 11:52
Looks great! I hope this will make it into the RE2.0 release ;)

**Comment by qreeves** [comment] 2019-11-11 13:34
Merged in, but... can you change the purple coloured bits covered by the alpha channel in the mask to white? I'll tint these in software with the weapon colour from now on, and it looks a little strange when I do without it being a neutral colour.

**Comment by V-ktor** [comment] 2019-11-11 19:22
Here you go:
[rifle_no_purple.zip](https://github.com/redeclipse/world/files/3832900/rifle_no_purple.zip)

**Comment by molexted** [comment] 2019-11-11 20:03
This model looks a lot better than the original rifle model, but in doing so it draws more attention to itself than the forgettable original model.

![20191111113934](https://user-images.githubusercontent.com/23445929/68615415-e2264680-0477-11ea-9eb3-e3a29774090b.png)

In less contrasty lighting the model looks to be a rather middling and boring shade of gray. Perhaps make the model darker and more specular, to resemble this:
![20191111115939](https://user-images.githubusercontent.com/23445929/68616773-95903a80-047a-11ea-9459-cbd91db06113.png)

There's still a lot going on poly-wise with the intrusions but I simultaneously felt the side of the weapon was a bit boring, with the flat gray sides with little contrast.

**Comment by V-ktor** [comment] 2019-11-11 20:59
more contrasty textures:
[rifle_high_contrast.zip](https://github.com/redeclipse/world/files/3833222/rifle_high_contrast.zip)

Well, the sides of the weapon are flat. I'm not sure how it will look with round sides.

**Comment by molexted** [comment] 2019-11-14 20:34
It's not entirely that, but you may indeed want to consider smoother, rounded projections rather than the angular and cluttery objects added to fill space on the weapon. I would recommend trying to keep the features of the weapon as parallel as possible, rather than creating a bunch of confusing and cluttery visual lines that run perpendicular to each other (keeping things parallel also helps create the impression of length).

The problem is that the normal maps have no detail (do not simulate any surface texture) and as a result the skylump envmap provided creates moire patterns rather than a (janky) simulation of reflectivity. Additionally, with an entirely flat normal, the specular highlights are unnatural and jarring when turned up to useful levels. At the very minimum, and in the absence of larger scale normal map detail, the normal map should have some variation to represent the surface roughness (like that created by matte powder coating).

**Comment by Calinou** [comment] 2019-11-14 21:09
It might be a good idea to bake some ambient occlusion on the diffuse map too. It'd make shading look less abrupt on the model.

**Comment by SniperGoth** [comment] 2019-11-14 21:45
What Calinou said, it gives a huge difference when you have the AO baked on a diffuse. depending on the model complexity.

**Comment by V-ktor** [comment] 2019-11-15 20:29
I tried baking AO. It turned out somewhat noisy for some reason. Anyway, seems to work with some post processing. I also made a new UV map and changed the texturing a bit.
It looks much better already.
[rifle_new.zip](https://github.com/redeclipse/world/files/3853040/rifle_new.zip)

**Comment by SniperGoth** [comment] 2019-11-15 20:30
>  It turned out somewhat noisy for some reason

Bake it using high samples, that way you will get better results.  ^^

**Comment by V-ktor** [comment] 2019-11-15 21:45
It turned out the problem was another mesh that was not hidden for rendering.
[rifle_skin_ao.zip](https://github.com/redeclipse/world/files/3853259/rifle_skin_ao.zip)

**Comment by V-ktor** [comment] 2019-11-26 19:08
Here is the new zapper model. Actually the old new zapper model as I'm working on a smoother version.
[new_zapper.zip](https://github.com/redeclipse/world/files/3893590/new_zapper.zip)

**Comment by nonoesimposible** [comment] 2019-11-27 05:14
You might want to create a whole new issue for the new model, seeing that they are different models and different discussions.

**Comment by V-ktor** [comment] 2019-11-30 19:36
New, cleaner textures
[new_rifle.zip](https://github.com/redeclipse/world/files/3907467/new_rifle.zip)
![20191130203548](https://user-images.githubusercontent.com/12966454/69905246-1fb02c80-13b1-11ea-8b92-e2c4a4e42c7c.jpg)

**Comment by bonifarz** [comment] 2019-12-07 11:36
Good stuff, great to see you are still contributing new weapon assets!

**Comment by V-ktor** [comment] 2019-12-10 21:37
Darker textures
[new_rifle.zip](https://github.com/redeclipse/world/files/3947240/new_rifle.zip)
![20191210222548](https://user-images.githubusercontent.com/12966454/70570434-2d796500-1b9c-11ea-95dd-7b8c0525b58d.jpg)
![20191210222554](https://user-images.githubusercontent.com/12966454/70570435-2d796500-1b9c-11ea-9b06-f2292055fd0d.jpg)

**Closed** 2020-01-15 15:24 UTC
Labels: asset, release candidate, showcase
