### ISSUE TITLE
Ability to rotate playerpreview with mouse input?

### ISSUE THREAD

**Issue by Jigoku** [redeclipse/world#154] opened 2020-01-03 21:14 UTC
I don't know if this can be easily implemented in the cubescript UI as is, but i'll mention this as i saw several points of feedback from twitch/youtube clips over the past few weeks, where people mention "how do i stop the player spinning" when selecting vanities. There's a small level of frustration having to wait for the player to spin back around to see most vanities.

Could be worthwhile to be able to interrupt the spinning of the player model, and allow you to click/drag left or right over the model.

**Comment by Calinou** [comment] 2020-01-03 21:50
At the very least, we could make the preview clickable to stop/restart the rotation. We could also slow down the rotation speed slightly.

**Comment by qreeves** [comment] 2020-01-03 22:18
Duplicate of https://github.com/redeclipse/base/issues/44

**Closed by qreeves** 2020-01-03 22:18 UTC
Labels: feature request, suggestion
