### ISSUE TITLE
EU General Data Protection Regulation

### ISSUE THREAD

**Issue by IceflowRE** [redeclipse/world#59] opened 2018-05-24 19:10 UTC
## Foreword
This issue exist only due to the GDPR and is here to clarify and discusses:
- Is this project affected?
- If it is, how is it affected?
- What can we do to comply with this law.

Its an ongoing issues because i and maybe others arent lawyers and cannot see through the whole situation.
If you see one point is wrong or one point is missing write it, that i can edit the things below.
If we come to the point, that ~~the whole RE project is not affected or~~ we clarified it, we can close this issue.
Its better to be safe than unsure.

Usefull links:
[General Data Protection Regulation](https://gdpr-info.eu/)

[Help and Tips](https://ec.europa.eu/commission/priorities/justice-and-fundamental-rights/data-protection/2018-reform-eu-data-protection-rules_en)

Additional:
[qlstats.net shuts down on May 24, 2018](https://www.plusforward.net/quake/post/49410/qlstatsnet-shuts-down-on-May-24-2018/)

----

### Why?

1. This Regulation lays down rules relating to the protection of natural persons with regard to the processing of personal data and rules relating to the free movement of personal data.
2. This Regulation protects fundamental rights and freedoms of natural persons and in particular their right to the protection of personal data.
3. The free movement of personal data within the Union shall be neither restricted nor prohibited for reasons connected with the protection of natural persons with regard to the processing of personal data.

[~ Art. 1 GDPR](https://gdpr-info.eu/art-1-gdpr/)

### When?

This Regulation applies to the processing of personal data wholly or partly by automated means and to the processing other than by automated means of personal data which form part of a filing system or are intended to form part of a filing system.

[~ Art. 2 (1) GDPR](https://gdpr-info.eu/art-2-gdpr/)

### Who?

1. This Regulation applies to the processing of personal data in the context of the activities of an establishment of a controller or a processor in the Union, regardless of whether the processing takes place in the Union or not.
2. This Regulation applies to the processing of personal data of data subjects who are in the Union by a controller or processor not established in the Union, where the processing activities are related to: 
    a) the offering of goods or services, irrespective of whether a payment of the data subject is required, to such data subjects in the Union; or
    b) the monitoring of their behaviour as far as their behaviour takes place within the Union.

[~ Art. 3 (1, 2) GDPR](https://gdpr-info.eu/art-3-gdpr/)

### What is personal data?

‘personal data’ means any information relating to an identified or identifiable natural person (‘data subject’); an identifiable natural person is one who can be identified, directly or indirectly, in particular by reference to an identifier such as a name, an identification number, location data, an online identifier or to one or more factors specific to the physical, physiological, genetic, mental, economic, cultural or social identity of that natural person;

[~ Art. 4 (1) GDPR](https://gdpr-info.eu/art-4-gdpr/)

### Yes if
- a server host is inside the EU
- a player is inside the EU
- ❓ website (github.com cookies)
- RE stats website (only registered eu players)

### Because
- RE is monitoring the behaviour european players
- RE processes personal data from european players
- ❓ RE is offering an service (the server) to people in the EU

### What is affected
1. registered alias
1. sending IPs to other players
with special rights
1. sending IPs to the master server
1. sending/ processing the match results of servers
1. sending/ processing the match results from registered players
1. public ip ban list (only if its an eu player)
1. website (github.com cookies)
1. maybe logging of the chat/connects/disconnects from a server

## What can we do to make it legal/ safe for the EU community?

- writing a privacy policy for the webiste containing
    - Which personal data is proceeded why and how long?
    - Usage of cookies
- Make an agreement for the players, like the `Multiplayer Guidelines`
    - Which contains:
        - Which data is collected/ proceeded
        - Why it is collected/ proceeded
        - How long is it saved
        - How can the collected data downloaded
        - How can the collected data deleted
        - Checkbox/ Button for agree
- ❓ Additional agreement for server hosts, to delete the log after `x` days
- Hash the IP banlist, to anonymize it and check only against the hash
- Download/ Delete request of your own data for the statistic database
- ❓ prevent sending IPs to other players

Just ban/ ostracize the eu community.

---

PS.
- as a result of this ~~unclear~~ situation i will shutdown my `Blizzard` servers until ~~this issue is clarified.~~
*RE complies with the GDPR.* 
- sorry for my english, i give my best

**Comment by lambda-11235** [comment] 2018-05-24 21:48
Ban/ostricize isn't really an option, since over half the community is in the EU.

**Comment by JeffBobbo** [comment] 2018-05-24 23:47
It should be noted that IPs are no longer distributed to players who don't have any kind of privileges (not sure about moderator, but operator+).

While the master server may store stuff, this will also apply to the individual server hosts (unless that stuff isn't logged any more, but pretty sure it is).

**Comment by qreeves** [comment] 2018-05-31 07:15
I've refrained from commenting on this so far (no I'm not ignoring it), while I consider the legislation and find an appropriate response, but I think I have a few ideas on how to proceed. My following comments will address each section individually, as I formulate my ideas and look at each way we collect and use data.

**Comment by qreeves** [comment] 2018-05-31 08:47
**IP addresses and other data**

Currently, our ban list is public and contains a list of IP addresses of people who have violated the Multiplayer Guidelines. Unfortunately, there is currently no agreement that allows us to store and use this "identifiable information" as it isn't even covered in the Guidelines. There are also some concerns over divulging the IP address in the first place, and what information server owners might be obtaining.

First, I'd like to address the suggestion that we just simply hash IP addresses. I actually come from an IRCd development background where this is/was a common practice in order to hide IP addresses from regular users. The problem here is inherent with any method of trying to obscure IP addresses in an easily reproducible way, [Rainbow Tables](https://en.wikipedia.org/wiki/Rainbow_table). I won't go much into the details, but with a determinable number of IP addresses, it is way too easy to generate one of these tables to "re-identify" the data.

Secondly, simply making the list itself private won't work at all, because all servers are given this information in order to enforce the bans. Given the open source nature of the project, it would be easy for anyone to get this information when determined enough. Asking the master server to verify every connection will just slow down the connection process to the point of breaking, and transmits data to us we don't necessarily need, increasing our liability.

We need to be able to moderate our community effectively, and hiding information from everyone serves counter to that purpose, so all this means we can't really change the way we handle IP addresses, bans, etc. The only sure fire approach is to create a proper privacy policy and require users to "opt-in" before being allowed to use the online functionality, in which they must agree to the dissemination of information or be locked out of playing online ("online play agreement"). NOTE: This is separate from the optional statistics collection ("statistics agreement"), so there'd be two opt-in settings covering all possible information.

In addition, there is the matter of what information a server owner might be obtaining (and storing) during the process of a user connecting to and playing on it. It is unreasonable to think that an open source project could do much about this, because, at the very lowest level, information like IP addresses and who they're associated with is easily obtainable even without modifying the source code.

I'm aware that we are also transmitting data about certain system configuration parameters (Version and GPU info, etc) that are helpful when diagnosing problems and spotting people who evade bans. On our end, this isn't being stored anywhere so we're OK there, but it will appear in log files and in-game. It is likely that this information will be part of the things you must accept in the online play agreement.

Our policies will need to clearly outline all of this, and it will have to be up to the server owners to ensure they personally are complying with the GDPR. We can't be held responsible for third party "breaches", and the biggest reason we will need to block people from playing online unless they agree to these possibilities along with the information they are sharing.

**Comment by lambda-11235** [comment] 2018-06-01 01:21
@qreeves What if we sent a hash and a salt to each server, where the salt is randomized each time? That way as the band list changes it won't be easy to identify IPs.

**Comment by qreeves** [comment] 2018-06-01 06:04
@lambda-11235 I understand this probably comes from reading the Wikipedia article, but it is just more data which is stored and then transmitted publicly to servers (which are easy to setup and modify). Knowing the parameters at any time, it is reasonable to assume a modern computer could generate a new rainbow table (or even on the fly) rather quickly and thus circumvent privacy. This approach is more for when you are storing passwords in a private database for security, it does not address individual privacy rights as defined in the GDPR.

**Closed** 2020-01-15 15:30 UTC
Labels: WIP, discussion
